# Generated by Django 4.1 on 2023-08-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_authornotes_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='protected',
            field=models.BooleanField(default=False),
        ),
    ]
