# Generated by Django 4.1 on 2023-08-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_author_protected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='protected',
        ),
    ]
