# Generated by Django 4.1 on 2023-08-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_author_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_protect',
            field=models.BooleanField(default=False),
        ),
    ]
